johanna-maier/you-go

- Gemfile.lock
- app/models/booking.rb
- app/models/favourite.rb
- app/models/offer.rb
- app/models/review.rb
- app/models/user.rb
- db/migrate/20220514105144_add_columns_to_users.rb
- db/migrate/20220514105828_create_offers.rb
- db/migrate/20220514110731_add_user_ref_to_offers.rb
- db/migrate/20220514111939_create_reviews.rb
- db/migrate/20220514112335_create_favourites.rb
- db/migrate/20220514112758_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
- test/models/favourite_test.rb
- test/models/offer_test.rb
- test/models/review_test.rb
1. added offer and review model and updated user model
2. added favourites and bookings models
> Creating models

- config/environments/development.rb
- config/storage.yml
- db/migrate/20220514104813_create_active_storage_tables.active_storage.rb
- db/schema.rb
Added what was needed in Config
> Added Active Storage

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220514104813_create_active_storage_tables.active_storage.rb
- db/schema.rb
Added Better Errors gem to Gemfile
> Better errors

- app/controllers/offers_controller.rb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/offers_controller_test.rb
in addition to what the title says fixed an error in schema file - it was a result of previous merge, an "end" was missing
> Added a basic Offers controller with basic routes and #index #show views

- Gemfile.lock
- app/models/offer.rb
- app/models/user.rb
- db/schema.rb
- allow_nil must be set to 'true' to make certain properties not mandatory (price, capacity etc.)
- pending question - should 'tag' for an offer be optional too ?
> allowed nil values to make properties optional

- app/controllers/application_controller.rb
Added a missing rescue method for Pundit to ApplicationController
> Added a missing rescue method for Pundit

- app/assets/stylesheets/components/_icons_container.scss
- app/assets/stylesheets/components/_index.scss
- app/views/offers/index.html.erb
Added a basic Icons Bar as Partial and to Index page
> Added basic Icons Bar as Partial

- app/assets/stylesheets/components/_basic_offer_card.scss
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_basic_offer_card.html.erb
Added offer cards to index page and connected to DB.
> Added offer cards to index page and connected to DB.

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/shared/_basic_offer_card.html.erb
- app/views/shared/_navbar.html.erb
**Navbar**
- removed extra links
- linked logo to Home
- made Navbar sticky (also the transparent version)
- because of that: added a negative margin to Banner, so it'd go all the way to the top
**Home**
- removed rounding of bottom edges from .search-card
**Icons**
- added and styled a Messages icon on Navbar
- changes Search icon color to $icon-gray (was too prominent)
- changed Fav icon to empty heart + styled it in _card
- 
s
> Cleaned up Navbar and changed heart to icon

- app/javascript/controllers/insert_review_controller.js
- app/views/offers/show.html.erb
The 'no reviews yet' message was not getting removed when the first review for an offer was added. Fixed.
> fixed issue when first review is added

- Gemfile
- Gemfile.lock
> Added binding_of_caller in Gemfile to inspect variables upon raise

- Gemfile.lock
- app/assets/stylesheets/components/_cards.scss
- app/controllers/likes_controller.rb
- app/javascript/controllers/add_favourite_controller.js
- app/models/like.rb
- app/models/user.rb
- app/policies/application_policy.rb
- app/policies/like_policy.rb
- app/views/likes/_grey_icon.html.erb
- app/views/likes/_red_icon.html.erb
- app/views/likes/create.json.jbuilder
- app/views/likes/destroy.json.jbuilder
- app/views/shared/_basic_offer_card.html.erb
- config/routes.rb
- db/migrate/20220521110853_create_likes.rb
- db/migrate/20220521145829_drop_favourites_table.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/likes_controller_test.rb
- test/models/like_test.rb
- test/policies/like_policy_test.rb
Add /remove favourites using AJAX and JSON
- added new routes, controller, and models
- Previous table 'favourites' was dropped and a new table called likes was added (db migrations for the same)
- added Pundit policy for likes (fixed bug in ApplicationPolicy file)
Known issues 
- clicking on heart icon when user is not logged will raise and error on the server
- at present we display the same offer card twice on the Home Page. This leads to an inconsistent state.
Pending - 'add /remove to wishlist ' from the offer show page
> Add to wishlist feature

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/dashboard_controller.rb
- app/policies/dashboard_policy.rb
- app/views/dashboard/index.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/dashboard_controller_test.rb
- test/policies/dashboard_policy_test.rb
> Dashboard skeleton WIP

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/dashboards/dashboard.html.erb
- app/views/shared/_basic_offer_card.html.erb
- db/seeds.rb
changed the button, the capitalization of the text, the font colors...to be continued
> first part of some changes

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/controllers/dashboard_controller.rb
- app/controllers/likes_controller.rb
- app/javascript/controllers/edit_profile_controller.js
- app/javascript/controllers/tabs_controller.js
- app/policies/dashboard_policy.rb
- app/policies/user_policy.rb
- app/views/dashboard/_bookings.html.erb
- app/views/dashboard/_conversations.html.erb
- app/views/dashboard/_profile.html.erb
- app/views/dashboard/_wishlist.html.erb
- app/views/dashboard/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
- test/policies/user_policy_test.rb
Still WIP (sport category selection on profile page still pending)
- switching tabs with JS
- placeholder  views for booking / wishlist and conversations
Note: category icons are not being rendered correctly since not all of the icons being used are free. Need to double check all icons in seed file.
> Dashboard - profile page

- app/assets/stylesheets/components/_buttons.scss
- app/controllers/offers_controller.rb
- app/models/offer.rb
- app/models/tag.rb
- app/views/dashboard/_profile.html.erb
- app/views/offers/_offer_details_card.html.erb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- app/views/reviews/_form_review.html.erb
- app/views/shared/_basic_offer_card.html.erb
- app/views/shared/_booking_popup.html.erb
- app/views/shared/_category_card.html.erb
- db/seeds.rb
- lib/tasks/fake-offer-seed.rake
- Added new category search
- Update links
- Fixed icons
- Updated seeds
> Added new category search, update links, fixed icons, updated seeds.

- app/controllers/messages_controller.rb
- app/models/conversation.rb
I won't explain, lol - but it works now.
> Fixed the last bug. Now it REALLY should work.

- db/seeds.rb
> fixed seed extensions

- app/controllers/conversations_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/messages_controller.rb
- app/views/conversations/_message_form.html.erb
- app/views/conversations/show.html.erb
- app/views/dashboard/_conversation-details.html.erb
- app/views/dashboard/_conversations.html.erb
- app/views/shared/_conversation_card.erb
- app/views/shared/_message_card.html.erb
A lot of tiny changes. Result: Conversations work on dashboard.
!!! Everyhting's still hardcoded, so the path to START a conversation for testing is localhost:3000/conversations !!!
That last bit coming up next.
> Functionality to 80% done, connected to dashboard

- app/controllers/conversations_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/offers_controller.rb
- app/models/conversation.rb
- app/views/conversations/_start_conversation_form.html.erb
- app/views/conversations/index.html.erb
- app/views/dashboard/_conversations.html.erb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- app/views/shared/_booking_popup.html.erb
In addition: removed message field from Booking modal.
Currently a lot is simply commented out. I'm still not sure, if we need it - will evaluate later.
At this point you can send a message to the organizer. The msg box needs styling though.
> Basic Message form integrated with Offer in Offer#Show

- app/controllers/conversations_controller.rb
- app/models/conversation.rb
- db/migrate/20220605061113_remove_index_contraint_from_conversations.rb
- db/schema.rb
Step by step working on adjusting the functionality to our specific situation.
This is one of the steps.
> Removed faulty contraint from Convo Schema

- app/controllers/conversations_controller.rb
- app/controllers/messages_controller.rb
- app/models/conversation.rb
Adjusted the logic of the system to fit our situation. Now works without errors from all ends.
> Final bugfixes and adjustments

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_icons_container.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/dashboard_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/offers_controller.rb
- app/controllers/pages_controller.rb
- app/views/conversations/_message_form.html.erb
- app/views/conversations/_start_conversation_form.html.erb
- app/views/dashboard/_bookings.html.erb
- app/views/dashboard/_conversation-details.html.erb
- app/views/dashboard/_conversations.html.erb
- app/views/dashboard/_profile.html.erb
- app/views/dashboard/_wishlist.html.erb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- app/views/pages/home.html.erb
- app/views/reviews/_form_review.html.erb
- app/views/shared/_booking_card.html.erb
- app/views/shared/_category_card.html.erb
- app/views/shared/_conversation_card.erb
- app/views/shared/_wishlist_card.erb
Many small layout changes: Align all dashboard cards, scrollable icons, messaging views and forms.
> Many small layout changes: Align all dashboard cards, scrollable icons, messaging views and forms.

- app/controllers/conversations_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/messages_controller.rb
- app/models/conversation.rb
- app/views/dashboard/_conversation-details.html.erb
Fixed: 
- User couldn't send another msg from Offers#Show, if that convo already existed. Now they can.
Refactored: 
- conversations_controller (removed all unused parts)
- dashboard_controller (all the long if-else into 4 private methods)
- removed @messages variable from dashboard #index. all respective msgs are now accessed through @conversation variable in conversation-details instead
> last bugfix + some refactoring

- app/views/dashboard/_conversation-details.html.erb
Added a link to Offer Show page to the heading of Conversation in _conversation-details
> Added link_to Offer#Show to h2 in convo details

- app/controllers/conversations_controller.rb
removed unuses private method from conversations_controller
> removed last unuse method from conversations_controller

- app/assets/stylesheets/pages/_dashboard.scss
reduced z-index to 1 for h2 in .conversation-details-box on Dashboard (was set to 50 before) to fix overlay
> reduced unnecceserily high z-index for one element

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/shared/_booking_popup.html.erb
- booking button
- simple styling of alerts
- shadow to make white heart visible on white cards
> minor styling

- app/controllers/pages_controller.rb
Added real recommendation API: If user 66 is logged in, personal recommendations are shown. All other users get recommendations from user 70.
> Added real recommendation API: If user 66 is logged in, personal recommendations are shown. All other users get recommendations from user 70.

- app/controllers/bookings_controller.rb
- app/controllers/dashboard_controller.rb
- app/javascript/controllers/tabs_controller.js
- app/models/booking.rb
- app/views/dashboard/_profile.html.erb
- app/views/shared/_navbar.html.erb
1. Booking modal was crashing the app if number of participants was left blank.
-> modified validation for number_of_participants to avoid this scenario (this is a temporary fix, the actual issue still needs to be addressed, i.e the correct partial to render in case of error )
2. similar issue of profile screen - also a partial fix for the time being 
3.  some code cleanup
> booking modal error handled

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_favourite.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/javascript/controllers/add_favourite_controller.js
- app/views/likes/_grey_icon.html.erb
- app/views/likes/_red_icon.html.erb
- app/views/offers/show.html.erb
- app/views/shared/_footer.html.erb
- enabled wishlist feature on offer show page
> Show page wishlist

- app/assets/stylesheets/components/_icons_container.scss
- app/assets/stylesheets/components/_index_container.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/offers/index.html.erb
Everything is more spaced out. But the map has a glitch while scrolling.
> adjusted spacing on offer index page

- app/assets/stylesheets/components/_alert.scss
- app/controllers/bookings_controller.rb
to be merged if we want this flow for demo
> removed redirect after booking
